<a href="https://colab.research.google.com/github/HariNiveditha/MARG/blob/main/MARG_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving master_dataset (1).csv to master_dataset (1).csv

In [ ]:
import pandas as pd

df = pd.read_csv("master_dataset (1).csv")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 23115
Columns: 20

In [ ]:
df.head()

/usr/local/lib/python3.13/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,report_file,format,sl_no,project_name,agency,project_code,state,ministry,sector,approval_date,revised_start_date,target_doc,revised_doc,original_cost_cr,revised_cost_cr,cumulative_expenditure_cr,physical_progress_pct,participating_states,is_multi_state,state_standardized
0,FRApril2025.pdf,old,1,CONSTRUCTION OF NEW INTEGRATED TERMINAL BUILDI...,AAI,N04000073,ASSAM,NaN,CIVIL AVIATION,10-2013,NaN,9/2018,6/2023,417.23,707.73,698.80,100.00,['ASSAM'],False,ASSAM
1,FRApril2025.pdf,old,2,LUDHIANA KILA RAIPUR (19 KMS) WITH FREIGHT LIN...,NR,N22000584,ASSAM,NaN,RAILWAYS,3-2019,NaN,3/2025,12/2025,235.72,N.A.,54.28,55.00,['ASSAM'],False,ASSAM
2,FRApril2025.pdf,old,3,"2 LANE WITH HARD SHOLDER , REHABILITATION AND ...",NHIDCL,N24000745,ASSAM,NaN,RAILWAYS,3-2017,NaN,12/2019,3/2023,409.85,N.A.,214.23,95.10,['ASSAM'],False,ASSAM
3,FRApril2025.pdf,old,4,REHABILITATION AND UP GRADATION OF SECTION FRO...,NHIDCL,N24000749,ASSAM,NaN,RAILWAYS,3-2018,NaN,9/2020,11/2022,234.27,N.A.,126.50,82.93,['ASSAM'],False,ASSAM
4,FRApril2025.pdf,old,5,Rehabilitation and up gradation to 2 lane with...,MoRTH,N24000820,ASSAM,NaN,RAILWAYS,11-2017,NaN,11/2019,N.A.,237.80,N.A.,222.13,98.23,['ASSAM'],False,ASSAM

In [ ]:
print(df.columns.tolist())

['report_file', 'format', 'sl_no', 'project_name', 'agency', 'project_code', 'state', 'ministry', 'sector', 'approval_date', 'revised_start_date', 'target_doc', 'revised_doc', 'original_cost_cr', 'revised_cost_cr', 'cumulative_expenditure_cr', 'physical_progress_pct', 'participating_states', 'is_multi_state', 'state_standardized']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23115 entries, 0 to 23114
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   report_file                23115 non-null  object
 1   format                     23115 non-null  object
 2   sl_no                      23115 non-null  int64
 3   project_name               23115 non-null  object
 4   agency                     22991 non-null  object
 5   project_code               15497 non-null  object
 6   state                      23115 non-null  object
 7   ministry                   18213 non-null  object
 8   sector                     23115 non-null  object
 9   approval_date              22514 non-null  object
 10  revised_start_date         17478 non-null  object
 11  target_doc                 23115 non-null  object
 12  revised_doc                23104 non-null  object
 13  original_cost_cr           23115 non-null  object
 14  revised_cost_cr            23115 non-null  object
 15  cumulative_expenditure_cr  23115 non-null  object
 16  physical_progress_pct      23112 non-null  object
 17  participating_states       23115 non-null  object
 18  is_multi_state             23115 non-null  bool
 19  state_standardized         23115 non-null  object
dtypes: bool(1), int64(1), object(18)
memory usage: 3.4+ MB

In [ ]:
missing_report = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percentage": (df.isnull().sum() / len(df) * 100).round(2)
})

missing_report.sort_values("missing_count", ascending=False)

                           missing_count  missing_percentage
project_code                        7618               32.96
revised_start_date                  5637               24.39
ministry                            4902               21.21
approval_date                        601                2.60
agency                               124                0.54
revised_doc                           11                0.05
physical_progress_pct                  3                0.01
report_file                            0                0.00
project_name                           0                0.00
sl_no                                  0                0.00
format                                 0                0.00
state                                  0                0.00
target_doc                             0                0.00
sector                                 0                0.00
revised_cost_cr                        0                0.00
original_cost_cr                       0                0.00
cumulative_expenditure_cr              0                0.00
participating_states                   0                0.00
is_multi_state                         0                0.00
state_standardized                     0                0.00

In [ ]:
for col in df.columns:
    values = df[col].astype(str).str.strip().str.lower()

    fake_missing = values.isin([
        "n.a.",
        "n.a",
        "na",
        "n/a",
        "-",
        "--",
        ""
    ]).sum()

    if fake_missing > 0:
        print(f"{col}: {fake_missing}")

agency: 7236
revised_doc: 8321
revised_cost_cr: 3782
physical_progress_pct: 455

In [ ]:
for col in ["agency", "revised_doc", "revised_cost_cr", "physical_progress_pct"]:
    print("\n==========", col, "==========")
    print(
        df[col]
        .astype(str)
        .str.strip()
        .value_counts()
        .head(15)
    )

========== agency ==========
agency
-                                                      7236
MoRTH                                                  1402
NHAI                                                   1305
NHIDCL                                                  832
National Highways Authority of India [NHAI]             608
Power Grid Corporation of India Limited [POWERGRID]     427
Ministry of Petroleum & Natural Gas                     252
Western Coalfields Limited [WCL]                        217
PGCIL                                                   190
Airport Authority of India [AAI]                        170
Ministry of Coal                                        164
Ministry of Housing & Urban Affairs                     138
East Coast Railway [ECoR] - II                          128
South Central Railway [SCR] - II                        126
MinistryofPetroleumNaturalGas                           125
Name: count, dtype: int64

========== revised_doc ==========
revised_doc
-          5084
N.A.       3237
03/2026    1185
06/2026    1124
12/2026    1019
03/2027     815
12/2025     739
05/2026     538
08/2026     534
07/2026     467
09/2026     405
06/2027     345
04/2026     342
10/2026     341
12/2027     340
Name: count, dtype: int64

========== revised_cost_cr ==========
revised_cost_cr
N.A.      3782
325         38
410.26      26
349.22      25
297         24
825         24
6700        24
262         23
370         23
385         23
1813        22
210         22
3685        21
205         21
611.74      21
Name: count, dtype: int64

========== physical_progress_pct ==========
physical_progress_pct
0         1350
100        655
100.00     392
99         390
-          306
98         280
95         259
97         251
96         236
80         228
90         203
93         198
92         184
1          171
82         167
Name: count, dtype: int64

In [ ]:
import numpy as np

missing_values = ["-", "N.A.", "N.A", "NA", "N/A", "--", ""]

df = df.replace(missing_values, np.nan)

In [ ]:
df.isnull().sum().sort_values(ascending=False)

revised_doc                  8332
project_code                 7618
agency                       7360
revised_start_date           5637
ministry                     4902
revised_cost_cr              3782
approval_date                 601
physical_progress_pct         458
project_name                    0
sl_no                           0
format                          0
report_file                     0
target_doc                      0
sector                          0
state                           0
original_cost_cr                0
cumulative_expenditure_cr       0
participating_states            0
is_multi_state                  0
state_standardized              0
dtype: int64

In [ ]:
numeric_cols = [
    "original_cost_cr",
    "revised_cost_cr",
    "cumulative_expenditure_cr",
    "physical_progress_pct"
]

for col in numeric_cols:
    print("\n==========", col, "==========")
    print(df[col].dropna().head(15).tolist())

========== original_cost_cr ==========
['417.23', '235.72', '409.85', '234.27', '237.80', '257.34', '401.00', '371.80', '207.54', '183.47', '611.80', '347.15', '265.91', '655.34', '588.72']

========== revised_cost_cr ==========
['707.73', '401.00', '207.99', '154.01', '347.15', '656.39', '220.00', '307.66', '342.41', '290.00', '2,171.00', '703.00', '244.10', '1,718.59', '873.92']

========== cumulative_expenditure_cr ==========
['698.80', '54.28', '214.23', '126.50', '222.13', '214.90', '260.08', '0.00', '16.21', '1.45', '433.85', '72.12', '39.49', '366.21', '630.55']

========== physical_progress_pct ==========
['100.00', '55.00', '95.10', '82.93', '98.23', '100.00', '97.00', '2.11', '35.50', '25.27', '73.00', '43.00', '27.00', '95.00', '100.00']

In [ ]:
numeric_cols = [
    "original_cost_cr",
    "revised_cost_cr",
    "cumulative_expenditure_cr",
    "physical_progress_pct"
]

for col in numeric_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(",", "", regex=False)
    )
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [ ]:
df[numeric_cols].dtypes

original_cost_cr             float64
revised_cost_cr              float64
cumulative_expenditure_cr    float64
physical_progress_pct        float64
dtype: object

In [ ]:
df[numeric_cols].describe()

,original_cost_cr,revised_cost_cr,cumulative_expenditure_cr,physical_progress_pct
count,23115.000000,19333.000000,23115.000000,22657.000000
mean,2045.946349,2494.404474,1228.941445,58.609111
std,5630.392289,8179.427998,5272.131277,34.603874
min,68.000000,0.100000,-4.880000,0.000000
25%,350.000000,360.880000,66.050000,26.000000
50%,755.260000,813.030000,260.020000,67.000000
75%,1588.550000,1832.660000,765.610000,91.000000
max,150000.000000,188000.000000,124623.000000,202.000000

In [ ]:
df[numeric_cols].isnull().sum()

original_cost_cr                0
revised_cost_cr              3782
cumulative_expenditure_cr       0
physical_progress_pct         458
dtype: int64

In [ ]:
invalid_progress = df[
    (df["physical_progress_pct"] < 0) |
    (df["physical_progress_pct"] > 100)
]

print("Invalid rows:", len(invalid_progress))

invalid_progress[
    [
        "project_name",
        "project_code",
        "report_file",
        "physical_progress_pct"
    ]
].sort_values("physical_progress_pct", ascending=False)

Invalid rows: 1

,project_name,project_code,report_file,physical_progress_pct
4896,UP-GRADATION OF BLAST FURNACE NO. 3 AT DURGAPU...,N12000139,FR_May2025.pdf,202.0

In [ ]:
df[df["physical_progress_pct"] < 0][
    [
        "project_name",
        "project_code",
        "report_file",
        "physical_progress_pct"
    ]
]

Empty DataFrame
Columns: [project_name, project_code, report_file, physical_progress_pct]
Index: []

In [ ]:
df[df["cumulative_expenditure_cr"] < 0][
    [
        "project_name",
        "project_code",
        "report_file",
        "cumulative_expenditure_cr"
    ]
]

,project_name,project_code,report_file,cumulative_expenditure_cr
11875,4L PS from Ch. 94.030 in Jabugam Village to Ch...,618930,FlashReport_January_2026.pdf,-4.88
12305,4L of Padalur - Trichy section from km. 285.00...,619113,FlashReport_January_2026.pdf,-0.08

In [ ]:
expenditure_issue = df[
    df["cumulative_expenditure_cr"] > df["original_cost_cr"]
]

print("Expenditure > original cost:",
      len(expenditure_issue))

expenditure_issue[
    [
        "project_name",
        "project_code",
        "original_cost_cr",
        "revised_cost_cr",
        "cumulative_expenditure_cr",
        "physical_progress_pct"
    ]
].head(20)

Expenditure > original cost: 2436

,project_name,project_code,original_cost_cr,revised_cost_cr,cumulative_expenditure_cr,physical_progress_pct
0,CONSTRUCTION OF NEW INTEGRATED TERMINAL BUILDI...,N04000073,417.23,707.73,698.80,100.00
14,CONSTRUCTION OF PERMANENT CAMPUS FOR IISER AT ...,N42000007,588.72,656.39,630.55,100.00
40,CONSTRUCTION OF TIMMAPURAM TO GURJANAPALLE SEC...,N24000964,350.61,NaN,407.92,98.00
49,6L OF VARADHARAJULA TO KUMARAJAPET FROM KM 0.0...,N24001820,1484.83,NaN,1493.57,87.50
50,BANGALORE CHENNAI EXPRESSWAY (PHASE-II PKG-III...,N24001821,1137.74,NaN,1256.44,94.60
51,BANGALORE CHENNAI EXPRESSWAY (PHASE-II PKG-I) ...,N24001822,1075.27,NaN,1092.90,81.50
110,POLAVARAM IRRIGATION PROJECT,N30000002,10151.04,NaN,23775.68,75.68
111,CONSTRUCTION OF NEW GREEN FIELD AIRPORT AT HOL...,N04000092,645.63,NaN,690.39,99.50
112,SUBANSIRI LOWER H.E.P (8X250 MW) (NHPC),180100221,6285.33,NaN,24022.52,96.20
126,CONSTRUCTION OF NEW INTEGRATED TERMINAL BUILDI...,N04000083,1142.00,NaN,1850.93,86.95
131,NUMALIGARH REFINERY EXPANSION PROJECT 6 MMTPA ...,N16000379,12366.00,NaN,15412.49,73.06
145,4 LANING OF JORHAT TO JHANJI SECTION FROM KM. ...,N24000319,437.39,NaN,547.95,96.13
146,FOUR LANING OF JHANJHI JN TO DEMOW SECTION FRO...,N24000320,463.49,NaN,490.44,75.52
149,4 LANING OF NH-37 SECTION BETWEEN DEMOW TO END...,N24000582,294.17,NaN,381.37,97.63
163,"6L STANDALONE FLYOVERS AT RAHA, DEMOW, BORGHAT...",N24001545,175.00,NaN,200.80,100.00
201,BARH STPP(3X660MW) NTPC,180100242,8692.97,21312.11,22290.14,95.00
202,BUXAR THERMAL POWER PLANT (1320 MW),N18000194,10439.09,NaN,11451.47,89.95
204,"HAJIPUR-SUGAULI VIA VAISHALI (NL), ECR",220100303,2066.78,2087.36,2294.71,73.00
205,NEW B.G. LINE FROM ARARIA TO GALGALIA (THAKURG...,N22000087,2650.00,2132.03,3787.25,90.00
206,SAKRI-HASANPUR ROAD (NL),N22000171,325.00,735.20,602.01,78.00

In [ ]:
df["progress_invalid_flag"] = (
    (df["physical_progress_pct"] < 0) |
    (df["physical_progress_pct"] > 100)
)

df.loc[df["progress_invalid_flag"], "physical_progress_pct"] = np.nan

In [ ]:
df["expenditure_invalid_flag"] = (
    df["cumulative_expenditure_cr"] < 0
)

df.loc[
    df["expenditure_invalid_flag"],
    "cumulative_expenditure_cr"
] = np.nan

In [ ]:
df["expenditure_above_original_flag"] = (
    df["cumulative_expenditure_cr"] >
    df["original_cost_cr"]
)

In [ ]:
df["expenditure_above_revised_flag"] = (
    df["revised_cost_cr"].notna() &
    (df["cumulative_expenditure_cr"] > df["revised_cost_cr"])
)

In [ ]:
print(
    "Expenditure > revised cost:",
    df["expenditure_above_revised_flag"].sum()
)

Expenditure > revised cost: 890

In [ ]:
df[df["expenditure_above_revised_flag"]][
    [
        "project_name",
        "project_code",
        "original_cost_cr",
        "revised_cost_cr",
        "cumulative_expenditure_cr",
        "physical_progress_pct"
    ]
].head(20)

,project_name,project_code,original_cost_cr,revised_cost_cr,cumulative_expenditure_cr,physical_progress_pct
201,BARH STPP(3X660MW) NTPC,180100242,8692.97,21312.11,22290.14,95.0
204,"HAJIPUR-SUGAULI VIA VAISHALI (NL), ECR",220100303,2066.78,2087.36,2294.71,73.0
205,NEW B.G. LINE FROM ARARIA TO GALGALIA (THAKURG...,N22000087,2650.00,2132.03,3787.25,90.0
207,ARARIA-SUPAUL (NL),N22000177,1605.17,1605.17,1654.14,65.0
209,SAMASTIPUR-DARBANGHA,N22000329,519.33,519.33,626.71,80.0
210,KIUL - GAYA DOUBLING PROJECT,N22000349,2462.11,1200.20,1833.59,99.0
211,RAMPUR DUMRA - TAL - RAJENDRAPUL DOUBLING INCL...,N22000350,2373.64,1491.47,1763.21,77.0
212,SAGAULI VALMIKINAGAR DOUBLING 109.7 KM,N22000472,1215.54,1215.54,1556.04,90.0
213,MUZAFFARPUR SAGAULI DOUBLING 100.60 KM,N22000473,1586.22,1185.73,1470.35,96.0
214,FATUHA-ISLAMPUR INCL. MM FOR EXTENSION OF NEW ...,N22000476,1473.30,803.09,2764.98,90.0
215,DARBHANGA - BYPASS LINE CONNECTING SHISHO HALT...,N22000523,983.62,253.23,417.57,100.0
237,BALANCE WORK OF 4- LANING OF PATNA-GAYA-DOBHI ...,N24001304,446.97,598.48,638.80,96.3
238,BALANCE WORK OF 4- L ANING OF PATNA-GAYA-DOBHI...,N24001305,464.09,605.53,698.25,97.3
278,"SEWER NETWORKS, SPS AND STP, MUNGER",N30000036,294.02,350.79,428.70,100.0
280,SEWERAGE SYSTEM WITH SEWER NETWORK PATNA KARMA...,N30000044,277.42,253.98,355.31,100.0
300,JHARSUGUDA-BILASPUR 4TH LINE,N22000484,2140.34,2135.34,2264.16,88.0
398,MEHSANA PALANPUR DOUBLING PROJECT 65.10 KMS,N22000505,537.31,537.31,844.55,100.0
401,RAJKOT-KANALUS (111.20 KM),N22000535,1080.58,1080.58,1337.86,65.0
402,HIMMATNAGAR-KHEDBRAHMA (54.83 KM),N22000537,354.99,482.42,834.53,84.0
407,VIJAPUR-AMBLIYASAN (41.53 KM),N22000547,309.81,415.38,565.62,85.0

In [ ]:
# Flag expenditure anomalies
df["expenditure_above_original_flag"] = (
    df["cumulative_expenditure_cr"] >
    df["original_cost_cr"]
)

df["expenditure_above_revised_flag"] = (
    df["revised_cost_cr"].notna() &
    (df["cumulative_expenditure_cr"] > df["revised_cost_cr"])
)

print("Expenditure > original cost:",
      df["expenditure_above_original_flag"].sum())

print("Expenditure > revised cost:",
      df["expenditure_above_revised_flag"].sum())

Expenditure > original cost: 2436
Expenditure > revised cost: 890

In [ ]:
df[df["expenditure_above_revised_flag"]][
    [
        "project_name",
        "project_code",
        "original_cost_cr",
        "revised_cost_cr",
        "cumulative_expenditure_cr",
        "physical_progress_pct"
    ]
].head(20)

,project_name,project_code,original_cost_cr,revised_cost_cr,cumulative_expenditure_cr,physical_progress_pct
201,BARH STPP(3X660MW) NTPC,180100242,8692.97,21312.11,22290.14,95.0
204,"HAJIPUR-SUGAULI VIA VAISHALI (NL), ECR",220100303,2066.78,2087.36,2294.71,73.0
205,NEW B.G. LINE FROM ARARIA TO GALGALIA (THAKURG...,N22000087,2650.00,2132.03,3787.25,90.0
207,ARARIA-SUPAUL (NL),N22000177,1605.17,1605.17,1654.14,65.0
209,SAMASTIPUR-DARBANGHA,N22000329,519.33,519.33,626.71,80.0
210,KIUL - GAYA DOUBLING PROJECT,N22000349,2462.11,1200.20,1833.59,99.0
211,RAMPUR DUMRA - TAL - RAJENDRAPUL DOUBLING INCL...,N22000350,2373.64,1491.47,1763.21,77.0
212,SAGAULI VALMIKINAGAR DOUBLING 109.7 KM,N22000472,1215.54,1215.54,1556.04,90.0
213,MUZAFFARPUR SAGAULI DOUBLING 100.60 KM,N22000473,1586.22,1185.73,1470.35,96.0
214,FATUHA-ISLAMPUR INCL. MM FOR EXTENSION OF NEW ...,N22000476,1473.30,803.09,2764.98,90.0
215,DARBHANGA - BYPASS LINE CONNECTING SHISHO HALT...,N22000523,983.62,253.23,417.57,100.0
237,BALANCE WORK OF 4- LANING OF PATNA-GAYA-DOBHI ...,N24001304,446.97,598.48,638.80,96.3
238,BALANCE WORK OF 4- L ANING OF PATNA-GAYA-DOBHI...,N24001305,464.09,605.53,698.25,97.3
278,"SEWER NETWORKS, SPS AND STP, MUNGER",N30000036,294.02,350.79,428.70,100.0
280,SEWERAGE SYSTEM WITH SEWER NETWORK PATNA KARMA...,N30000044,277.42,253.98,355.31,100.0
300,JHARSUGUDA-BILASPUR 4TH LINE,N22000484,2140.34,2135.34,2264.16,88.0
398,MEHSANA PALANPUR DOUBLING PROJECT 65.10 KMS,N22000505,537.31,537.31,844.55,100.0
401,RAJKOT-KANALUS (111.20 KM),N22000535,1080.58,1080.58,1337.86,65.0
402,HIMMATNAGAR-KHEDBRAHMA (54.83 KM),N22000537,354.99,482.42,834.53,84.0
407,VIJAPUR-AMBLIYASAN (41.53 KM),N22000547,309.81,415.38,565.62,85.0

In [ ]:
date_cols = [
    "approval_date",
    "revised_start_date",
    "target_doc",
    "revised_doc"
]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce")

print(df[date_cols].isna().sum())

approval_date          601
revised_start_date    5637
target_doc              34
revised_doc           8355
dtype: int64

/tmp/ipykernel_1305/867178189.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_1305/867178189.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_1305/867178189.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_1305/867178189.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors="coerce")

In [ ]:
for col in date_cols:
    print(f"\n--- {col} ---")
    print(df[col].dropna().astype(str).head(10).tolist())

print(df[date_cols].dtypes)

--- approval_date ---
['2013-10-01', '2019-03-01', '2017-03-01', '2018-03-01', '2017-11-01', '2017-11-01', '2017-02-01', '2024-12-01', '2018-02-01', '2018-02-01']

--- revised_start_date ---
['2024-01-01', '2020-09-01', '2023-08-01', '2018-03-01', '2025-04-01', '2024-07-01', '2018-10-01', '2019-12-01', '2025-07-01', '2022-07-01']

--- target_doc ---
['2018-09-01', '2025-03-01', '2019-12-01', '2020-09-01', '2019-11-01', '2019-11-01', '2019-07-01', '2026-02-01', '2025-09-01', '2025-11-01']

--- revised_doc ---
['2023-06-01', '2025-12-01', '2023-03-01', '2022-11-01', '2024-03-01', '2025-08-01', '2025-03-01', '2026-03-01', '2021-05-01', '2022-12-01']
approval_date         datetime64[ns]
revised_start_date    datetime64[ns]
target_doc            datetime64[ns]
revised_doc           datetime64[ns]
dtype: object

In [ ]:
print("Approval after target:",
      (df["approval_date"] > df["target_doc"]).sum())

print("Approval after revised start:",
      (df["approval_date"] > df["revised_start_date"]).sum())

print("Revised start after target:",
      (df["revised_start_date"] > df["target_doc"]).sum())

print("Revised start after revised completion:",
      (df["revised_start_date"] > df["revised_doc"]).sum())

print("Latest report file:")
print(df["report_file"].unique()[-5:])

print("\nLatest dates in dataset:")
for col in date_cols:
    print(col, df[col].max())

Approval after target: 24
Approval after revised start: 621
Revised start after target: 16
Revised start after revised completion: 3
Latest report file:
['FlashReport_March_2026.pdf' 'FlashReport_May2026.pdf'
 'FlashReport_November_2025.pdf' 'FlashReport_October_2025.pdf'
 'FlashReport_September_2025.pdf']

Latest dates in dataset:
approval_date 2027-03-01 00:00:00
revised_start_date 2027-07-01 00:00:00
target_doc 2056-12-01 00:00:00
revised_doc 2037-03-01 00:00:00

In [ ]:
for col in date_cols:
    print(f"\n===== {col} =====")
    print(
        df.loc[df[col].notna() & (df[col].dt.year > 2026),
               ["project_name", "project_code", "report_file", col]]
        .sort_values(col)
        .tail(20)
        .to_string(index=False)
    )

===== approval_date =====
                                       project_name project_code               report_file approval_date
Malkangiri Pandurangapuram new railway line project       616702 FlashReport_July_2025.pdf    2027-01-01
                                      SANGHMITRA OC       400136 FlashReport_July_2025.pdf    2027-03-01

===== revised_start_date =====
                                                                                                                                                                   project_name project_code                    report_file revised_start_date
                                                                                                                            Malkangiri Pandurangapuram new railway line project       616702    FlashReport_August_2025.pdf         2027-01-01
Integrated development of Outer Container Terminal and berth No. 1 though 5 NSD at KDS, SMPK on DBFOT basis through PPP mode (Syama Prasad Mookerjee Port Kolkata) (619229) (-)          NaN      FlashReport_June_2026.pdf         2027-02-01
    Integrated development of Outer Container Terminal and berth No. 1 though 5 NSD at KDS, SMPK on DBFOT basis through PPP mode (Syama Prasad Mookerjee Port Kolkata) (619229)        12116        FlashReport_May2026.pdf         2027-02-01
                                                                                                                                                                  SANGHMITRA OC       400136    FlashReport_August_2025.pdf         2027-03-01
                                                                                                                                                                  SANGHMITRA OC       400136 FlashReport_September_2025.pdf         2027-03-01
                                                                        Establishment of new GMC Kapurthala (Medical Education, Ministry of Health and Family Welfare) (707069)        11345      FlashReport_April2026.pdf         2027-07-01
                                                                        Establishment of new GMC Kapurthala (Medical Education, Ministry of Health and Family Welfare) (707069)          NaN  FlashReport_February_2026.pdf         2027-07-01
                                                                                                                                            Establishment of new GMC Kapurthala       707069   FlashReport_January_2026.pdf         2027-07-01
                                                                    Establishment of new GMC Kapurthala (Medical Education, Ministry of Health and Family Welfare) (707069) (-)          NaN      FlashReport_July_2026.pdf         2027-07-01
                                                                    Establishment of new GMC Kapurthala (Medical Education, Ministry of Health and Family Welfare) (707069) (-)          NaN      FlashReport_June_2026.pdf         2027-07-01
                                                                        Establishment of new GMC Kapurthala (Medical Education, Ministry of Health and Family Welfare) (707069)          NaN     FlashReport_March_2026.pdf         2027-07-01
                                                                        Establishment of new GMC Kapurthala (Medical Education, Ministry of Health and Family Welfare) (707069)        11345        FlashReport_May2026.pdf         2027-07-01

===== target_doc =====
                                                                                      project_name project_code                    report_file target_doc
                                                                              PARASCOLE JAMBAD OCP       616230      FlashReport_July_2025.pdf 2037-03-01
                                                                          CHUPERBHITA- SIMLONG OCP    N06000280               FR_JUNE_2025.pdf 2037-03-01
                                                                 CHUPERBHITA SIMLONG OCP MDO 6 MTY       616225 FlashReport_September_2025.pdf 2037-03-01
                                            CHUPERBHITA SIMLONG OCP MDO 6 (ECL - CIL) (616225) (-)          NaN      FlashReport_June_2026.pdf 2037-03-01
                                                                              PARASCOLE JAMBAD OCP       616230  FlashReport_November_2025.pdf 2037-03-01
                                                                              PARASCOLE JAMBAD OCP       616230   FlashReport_January_2026.pdf 2037-03-01
                                                                          CHUPERBHITA- SIMLONG OCP    N06000280                 FR_May2025.pdf 2037-03-01
Badam Coal Mining project of NTPC (National Thermal Power Corporation [NTPC]) (603293) (N18000367)          NaN        FlashReport_May2026.pdf 2056-12-01
                                                                 Badam Coal Mining project of NTPC       603293   FlashReport_January_2026.pdf 2056-12-01
                                                                 Badam Coal Mining project of NTPC       603293      FlashReport_July_2025.pdf 2056-12-01
                                                                 Badam Coal Mining project of NTPC       603293  FlashReport_December_2025.pdf 2056-12-01
Badam Coal Mining project of NTPC (National Thermal Power Corporation [NTPC]) (603293) (N18000367)          NaN      FlashReport_April2026.pdf 2056-12-01
                     Badam Coal Mining project of NTPC (National Thermal Power Corporation [NTPC])    N18000367     FlashReport_March_2026.pdf 2056-12-01
        Badam Coal Mining project of NTPC (National Thermal Power Corporation [NTPC]) (603293) (-)          NaN      FlashReport_July_2026.pdf 2056-12-01
                                                                 Badam Coal Mining project of NTPC       603293    FlashReport_August_2025.pdf 2056-12-01
                                                                 Badam Coal Mining project of NTPC       603293   FlashReport_October_2025.pdf 2056-12-01
        Badam Coal Mining project of NTPC (National Thermal Power Corporation [NTPC]) (603293) (-)          NaN      FlashReport_June_2026.pdf 2056-12-01
                                                                 Badam Coal Mining project of NTPC       603293  FlashReport_November_2025.pdf 2056-12-01
                                                                 Badam Coal Mining project of NTPC       603293 FlashReport_September_2025.pdf 2056-12-01
                     Badam Coal Mining project of NTPC (National Thermal Power Corporation [NTPC])    N18000367  FlashReport_February_2026.pdf 2056-12-01

===== revised_doc =====
                                                                                                                            project_name project_code                   report_file revised_doc
                                        City Gas Distribution Project at Pathankot District (MinistryofPetroleumNaturalGas) (709770) (-)          NaN     FlashReport_June_2026.pdf  2033-09-01
                                                                                                       CGD PROJECT AT PATHANKOT DISTRICT    N16000488              FR_JUNE_2025.pdf  2033-09-01
                                                     City Gas Distribution Project at Pathankot District (MinistryofPetroleumNaturalGas)    N16000488    FlashReport_March_2026.pdf  2033-09-01
                                                                                                       CGD PROJECT AT PATHANKOT DISTRICT    N16000488               FRApril2025.pdf  2033-09-01
                                                                                     City Gas Distribution Project at Pathankot District       709770  FlashReport_January_2026.pdf  2033-09-01
                                                     City Gas Distribution Project at Pathankot District (MinistryofPetroleumNaturalGas)    N16000488 FlashReport_February_2026.pdf  2033-09-01
                                City Gas Distribution Project at Pathankot District (MinistryofPetroleumNaturalGas) (709770) (N16000488)          NaN     FlashReport_April2026.pdf  2033-09-01
                                                                                     City Gas Distribution Project at Pathankot District       709770  FlashReport_October_2025.pdf  2033-09-01
                                                                                     City Gas Distribution Project at Pathankot District       709770   FlashReport_August_2025.pdf  2033-09-01
                                City Gas Distribution Project at Pathankot District (MinistryofPetroleumNaturalGas) (709770) (N16000488)          NaN       FlashReport_May2026.pdf  2033-09-01
City Gas Distribution Project at Jammu, Udhampur, Reasi, Samba and Kathua Districts (MinistryofPetroleumNaturalGas) (709773) (N16000527)          NaN     FlashReport_April2026.pdf  2034-09-01
                                                                                                          CGD PROJECT AT JAMMU DISTRICTS    N16000527              FR_JUNE_2025.pdf  2034-09-01
City Gas Distribution Project at Jammu, Udhampur, Reasi, Samba and Kathua Districts (MinistryofPetroleumNaturalGas) (709773) (N16000527)          NaN       FlashReport_May2026.pdf  2034-09-01
                     City Gas Distribution Project at Jammu, Udhampur, Reasi, Samba and Kathua Districts (MinistryofPetroleumNaturalGas)    N16000527    FlashReport_March_2026.pdf  2034-09-01
        City Gas Distribution Project at Jammu, Udhampur, Reasi, Samba and Kathua Districts (MinistryofPetroleumNaturalGas) (709773) (-)          NaN     FlashReport_June_2026.pdf  2034-09-01
                                                                                                          CGD PROJECT AT JAMMU DISTRICTS    N16000527                FR_May2025.pdf  2034-09-01
                                                                                                          CGD PROJECT AT JAMMU DISTRICTS    N16000527               FRApril2025.pdf  2034-09-01
                                                                                                                CHUPERBHITA- SIMLONG OCP    N06000280              FR_JUNE_2025.pdf  2037-03-01
                                                                                                                CHUPERBHITA- SIMLONG OCP    N06000280                FR_May2025.pdf  2037-03-01
                                                                                                                CHUPERBHITA- SIMLONG OCP    N06000280               FRApril2025.pdf  2037-03-01

In [ ]:
print(
    df.loc[
        df["target_doc"].dt.year > 2030,
        ["project_name", "project_code", "report_file", "target_doc"]
    ].to_string(index=False)
)

                                                                                                                             project_name project_code                    report_file target_doc
                                                                                    DIBANG MULTIPURPOSE PROJECT 2880 MW ARUNACHAL PRADESH    N18000362                FRApril2025.pdf 2032-02-01
                                                                                                           CGD PROJECT AT JAMMU DISTRICTS    N16000527                FRApril2025.pdf 2032-03-01
                                                                                                               KOTRE BASANTPUR PACHMO OCP    N06000237                FRApril2025.pdf 2032-03-01
                                                                                                                          CHANDRAGUPT OCP    N06000238                FRApril2025.pdf 2032-03-01
                                                                                                                      JHARKHAND LAIYO OCP    N06000240                FRApril2025.pdf 2031-03-01
                                                                                                                   EXPANSION OF KONAR OCP    N06000245                FRApril2025.pdf 2032-03-01
                                                                                                                 CHUPERBHITA- SIMLONG OCP    N06000280                FRApril2025.pdf 2037-03-01
                                                                                                                                URDHAN OC    N06000265                FRApril2025.pdf 2031-03-01
                                                                                                               BHUBANESWARI EXPANSION OCP    N06000286                FRApril2025.pdf 2031-03-01
                                                                                                              JEYPORE MALKANGIRI NEW LINE    N22000516                FRApril2025.pdf 2033-07-01
                                                                                                                     PARASCOLE JAMBAD OCP    N06000281                FRApril2025.pdf 2037-03-01
                                                                                                     CITY GAS DISTRIBUTION IN WEST BENGAL    N16000392                FRApril2025.pdf 2031-03-01
                                                                                    DIBANG MULTIPURPOSE PROJECT 2880 MW ARUNACHAL PRADESH    N18000362               FR_JUNE_2025.pdf 2032-02-01
                                                                                                           CGD PROJECT AT JAMMU DISTRICTS    N16000527               FR_JUNE_2025.pdf 2032-03-01
                                                                                                               KOTRE BASANTPUR PACHMO OCP    N06000237               FR_JUNE_2025.pdf 2032-03-01
                                                                                                                          CHANDRAGUPT OCP    N06000238               FR_JUNE_2025.pdf 2032-03-01
                                                                                                                      JHARKHAND LAIYO OCP    N06000240               FR_JUNE_2025.pdf 2031-03-01
                                                                                                                   EXPANSION OF KONAR OCP    N06000245               FR_JUNE_2025.pdf 2032-03-01
                                                                                                                 CHUPERBHITA- SIMLONG OCP    N06000280               FR_JUNE_2025.pdf 2037-03-01
                                                                                                                                URDHAN OC    N06000265               FR_JUNE_2025.pdf 2031-03-01
                                                                                                               BHUBANESWARI EXPANSION OCP    N06000286               FR_JUNE_2025.pdf 2031-03-01
                                                                                                              JEYPORE MALKANGIRI NEW LINE    N22000516               FR_JUNE_2025.pdf 2033-07-01
                                                                                                                     PARASCOLE JAMBAD OCP    N06000281               FR_JUNE_2025.pdf 2037-03-01
                                                                                    DIBANG MULTIPURPOSE PROJECT 2880 MW ARUNACHAL PRADESH    N18000362                 FR_May2025.pdf 2032-02-01
                                                                                                           CGD PROJECT AT JAMMU DISTRICTS    N16000527                 FR_May2025.pdf 2032-03-01
                                                                                                               KOTRE BASANTPUR PACHMO OCP    N06000237                 FR_May2025.pdf 2032-03-01
                                                                                                                          CHANDRAGUPT OCP    N06000238                 FR_May2025.pdf 2032-03-01
                                                                                                                      JHARKHAND LAIYO OCP    N06000240                 FR_May2025.pdf 2031-03-01
                                                                                                                   EXPANSION OF KONAR OCP    N06000245                 FR_May2025.pdf 2032-03-01
                                                                                                                 CHUPERBHITA- SIMLONG OCP    N06000280                 FR_May2025.pdf 2037-03-01
                                                                                                                                URDHAN OC    N06000265                 FR_May2025.pdf 2031-03-01
                                                                                                               BHUBANESWARI EXPANSION OCP    N06000286                 FR_May2025.pdf 2031-03-01
                                                                                                              JEYPORE MALKANGIRI NEW LINE    N22000516                 FR_May2025.pdf 2033-07-01
                                                                                                                     PARASCOLE JAMBAD OCP    N06000281                 FR_May2025.pdf 2037-03-01
                                                                                                     CITY GAS DISTRIBUTION IN WEST BENGAL    N16000392                 FR_May2025.pdf 2031-03-01
                                                                 TIKAK EXTENSION OCP (MIS MoCoal Integration Logins) (615820) (N06000290)          NaN      FlashReport_April2026.pdf 2031-07-01
                                                              PELMA OC MDO (South Eastern Coalfields Limited [SECL]) (616234) (N06000045)          NaN      FlashReport_April2026.pdf 2033-03-01
                                                                                        RPR FOR DURGAPUR OCP 10 MTY (SECL - CIL) (619171)        11842      FlashReport_April2026.pdf 2032-03-01
                                                                              KONAR EXPANSION OCP (Ministry of Coal) (400073) (N06000245)          NaN      FlashReport_April2026.pdf 2032-03-01
                                                                                            SANGHMITRA OC (Ministry of Coal) (400136) (-)          NaN      FlashReport_April2026.pdf 2032-03-01
                                                                                  CHANDRAGUPT OCP (Ministry of Coal) (400138) (N06000238)          NaN      FlashReport_April2026.pdf 2032-03-01
                                                                       KOTRE BASANTPUR PACHMO OCP (Ministry of Coal) (400139) (N06000237)          NaN      FlashReport_April2026.pdf 2032-03-01
                                                                                     EPR ASHOK OC (Ministry of Coal) (400155) (N06000247)          NaN      FlashReport_April2026.pdf 2031-03-01
                                                                              JHARKHAND-LAIYO OCP (Ministry of Coal) (400352) (N06000240)          NaN      FlashReport_April2026.pdf 2031-03-01
                                                   CHUPERBHITA SIMLONG OCP MDO 6 (Eastern Coal Fields Limited [ECL]) (616225) (N06000280)          NaN      FlashReport_April2026.pdf 2037-03-01
                                                    URDHAN EXPANSION OC COST PLUS (Western Coalfields Limited [WCL]) (615194) (N06000265)          NaN      FlashReport_April2026.pdf 2031-03-01
                                                                JAYANT EXPN. [20 TO 38 MTPA] (Northern Coalfields Limited [NCL]) (619032)        11593      FlashReport_April2026.pdf 2032-03-01
                                                             SAONER-III EXPN UG MINE 1.54 (Western Coalfields Limited [WCL]) (619055) (-)          NaN      FlashReport_April2026.pdf 2032-03-01
                                                                    SUBHADRA OCP (Mahanadi Coalfields Limited [MCL]) (400165) (N06000249)          NaN      FlashReport_April2026.pdf 2032-04-01
                                                  INTEGRATED KULDA GARJANBAHAL O (Mahanadi Coalfields Limited [MCL]) (616226) (N06000289)          NaN      FlashReport_April2026.pdf 2033-03-01
                                                                            BHUBANESWARI EXPN OCP 50 MTY (MCL - CIL) (616231) (N06000286)          NaN      FlashReport_April2026.pdf 2033-03-01
                                                            PARASCOLE JAMBAD OCP (Eastern Coal Fields Limited [ECL]) (616230) (N06000281)          NaN      FlashReport_April2026.pdf 2037-03-01
                                       Badam Coal Mining project of NTPC (National Thermal Power Corporation [NTPC]) (603293) (N18000367)          NaN      FlashReport_April2026.pdf 2056-12-01
                               Dibang Multipurpose Project (National Hydroelectric Power Corporation Limited [NHPC]) (602182) (N18000362)          NaN      FlashReport_April2026.pdf 2032-02-01
                                                700 MW Tato-II HE Project (North Eastern Electric Power Corporation Limited) (611716) (-)          NaN      FlashReport_April2026.pdf 2031-09-01
                                                                  Kalai-II Hydro Electric Project [1200 MW] (THDC India Limited) (619311)        12136      FlashReport_April2026.pdf 2032-10-01
                      Darlipali Super Thermal Power Project, Stage-II [1x800 MW] (National Thermal Power Corporation [NTPC]) (619056) (-)          NaN      FlashReport_April2026.pdf 2031-01-01
                                                               Bangalore Metro Rail Project - PHASE-3 (Bengaluru Metro Rail) (612878) (-)          NaN      FlashReport_April2026.pdf 2031-05-01
                           LUCKNOW METRO RAIL PROJECT PHASE-1B EAST WEST CORRIDOR (Uttar Pradesh metro rail corporation [UPMRC]) (619052)        11609      FlashReport_April2026.pdf 2031-04-01
 City Gas Distribution Project at Jammu, Udhampur, Reasi, Samba and Kathua Districts (MinistryofPetroleumNaturalGas) (709773) (N16000527)          NaN      FlashReport_April2026.pdf 2032-03-01
                  City Gas Distribution Project at Beed, Jalgaon and Jalna Districts (MinistryofPetroleumNaturalGas) (709771) (N16000487)          NaN      FlashReport_April2026.pdf 2031-09-01
                                 City Gas Distribution Maharashtra Natural Gas Limited (Ministry of Petroleum & Natural Gas) (701338) (-)          NaN      FlashReport_April2026.pdf 2031-06-01
                                 City Gas Distribution Project at Pathankot District (MinistryofPetroleumNaturalGas) (709770) (N16000488)          NaN      FlashReport_April2026.pdf 2033-09-01
City Gas Distribution Project at East Mednipore, West Mednipore & Jhargram Districts (MinistryofPetroleumNaturalGas) (709772) (N16000491)          NaN      FlashReport_April2026.pdf 2031-06-01
                                                       KHARSIA- NAYA RAIPUR-PARMALKASA 5th and 6th Line [278KM] (CAO/C/SECR) (617200) (-)          NaN      FlashReport_April2026.pdf 2031-03-01
                                    Chandargaon - Cansaulium Rail Flyover Project [16 Km] (South Western Railway [SWR] - II) (706865) (-)          NaN      FlashReport_April2026.pdf 2031-03-01
Bangalore-Satyamanglam New Line Project [260 Km] - Part Hejjala - Chamarajanagar [142 Km] (South Western Railway [SWR] - II) (705464) (-)          NaN      FlashReport_April2026.pdf 2031-12-01
                                              Gondia-Balharshah [Chanda Fort] Doubling [240 Km] (South East Central Railway) (617201) (-)          NaN      FlashReport_April2026.pdf 2031-03-01
                                       Jeypore-Malkanagiri New Railway Line Project (East Coast Railway [ECoR] - II) (705742) (N22000516)          NaN      FlashReport_April2026.pdf 2033-07-01
                                                                                                                      TIKAK EXTENSION OCP       615820    FlashReport_August_2025.pdf 2031-07-01
                                                                                                                             PELMA OC MDO       616234    FlashReport_August_2025.pdf 2033-03-01
                                                                                                                      KONAR EXPANSION OCP       400073    FlashReport_August_2025.pdf 2032-03-01
                                                                                                                            SANGHMITRA OC       400136    FlashReport_August_2025.pdf 2032-03-01
                                                                                                                          CHANDRAGUPT OCP       400138    FlashReport_August_2025.pdf 2032-03-01
                                                                                                               KOTRE BASANTPUR PACHMO OCP       400139    FlashReport_August_2025.pdf 2032-03-01
                                                                                                                      JHARKHAND-LAIYO OCP       400352    FlashReport_August_2025.pdf 2031-03-01
                                                                                                        CHUPERBHITA SIMLONG OCP MDO 6 MTY       616225    FlashReport_August_2025.pdf 2037-03-01
                                                                                                            URDHAN EXPANSION OC COST PLUS       615194    FlashReport_August_2025.pdf 2031-03-01
                                                                                                                             SUBHADRA OCP       400165    FlashReport_August_2025.pdf 2032-04-01
                                                                       INTEGRATED KULDA GARJANBAHAL O (Mahanadi Coalfields Limited (MCL))       616226    FlashReport_August_2025.pdf 2033-03-01
                                                                                                             BHUBANESWARI EXPN OCP 50 MTY       616231    FlashReport_August_2025.pdf 2033-03-01
                                                                                                                     PARASCOLE JAMBAD OCP       616230    FlashReport_August_2025.pdf 2037-03-01
                                                                                                        Badam Coal Mining project of NTPC       603293    FlashReport_August_2025.pdf 2056-12-01
                                                                                                              Dibang Multipurpose Project       602182    FlashReport_August_2025.pdf 2032-02-01
                                                                                                         Rakha Underground Mining Project       611798    FlashReport_August_2025.pdf 2033-03-01
                                                      City Gas Distribution Project at Jammu, Udhampur, Reasi, Samba and Kathua Districts       709773    FlashReport_August_2025.pdf 2032-03-01
                                                                       City Gas Distribution Project at Beed, Jalgaon and Jalna Districts       709771    FlashReport_August_2025.pdf 2031-09-01
                                                                                    City Gas Distribution Maharashtra Natural Gas Limited       701338    FlashReport_August_2025.pdf 2031-06-01
                                                                                      City Gas Distribution Project at Pathankot District       709770    FlashReport_August_2025.pdf 2033-09-01
                                                     City Gas Distribution Project at East Mednipore, West Mednipore & Jhargram Districts       709772    FlashReport_August_2025.pdf 2031-06-01
                                                                                 KHARSIA- NAYA RAIPUR-PARMALKASA 5th and 6th Line [278KM]       617200    FlashReport_August_2025.pdf 2031-03-01
                                                                                      Malkangiri Pandurangapuram new railway line project       616702    FlashReport_August_2025.pdf 2031-11-01
                                                                                             Jeypore-Malkanagiri New Railway Line Project       705742    FlashReport_August_2025.pdf 2033-07-01
                                                                                                                      TIKAK EXTENSION OCP       615820  FlashReport_December_2025.pdf 2031-07-01
                                                                                                                             PELMA OC MDO       616234  FlashReport_December_2025.pdf 2033-03-01
                                                                                                                      KONAR EXPANSION OCP       400073  FlashReport_December_2025.pdf 2032-03-01
                                                                                                                            SANGHMITRA OC       400136  FlashReport_December_2025.pdf 2032-03-01
                                                                                                                          CHANDRAGUPT OCP       400138  FlashReport_December_2025.pdf 2032-03-01
                                                                                                               KOTRE BASANTPUR PACHMO OCP       400139  FlashReport_December_2025.pdf 2032-03-01
                                                                                                                             EPR ASHOK OC       400155  FlashReport_December_2025.pdf 2031-03-01
                                                                                                                      JHARKHAND-LAIYO OCP       400352  FlashReport_December_2025.pdf 2031-03-01
                                                                                                            CHUPERBHITA SIMLONG OCP MDO 6       616225  FlashReport_December_2025.pdf 2037-03-01

In [ ]:
# Date quality flags
for col in date_cols:
    df[f"{col}_invalid_flag"] = (
        df[col].notna() &
        (df[col].dt.year > 2026)
    )

# Replace suspicious future dates with NaN
for col in date_cols:
    df.loc[df[f"{col}_invalid_flag"], col] = pd.NaT

# Check results
for col in date_cols:
    print(
        col,
        "invalid:",
        df[f"{col}_invalid_flag"].sum(),
        "| missing:",
        df[col].isna().sum()
    )

approval_date invalid: 2 | missing: 603
revised_start_date invalid: 12 | missing: 5649
target_doc invalid: 5740 | missing: 5774
revised_doc invalid: 4353 | missing: 12708

In [ ]:
for col in date_cols:
    df[f"{col}_invalid_flag"] = (
        df[col].notna() &
        (df[col].dt.year > 2026)
    )

for col in date_cols:
    print(col, df[f"{col}_invalid_flag"].sum())

approval_date 0
revised_start_date 0
target_doc 0
revised_doc 0

In [ ]:
import re
from datetime import datetime

def extract_report_date(filename):
    name = filename.lower()

    months = {
        "january": 1, "february": 2, "march": 3,
        "april": 4, "may": 5, "june": 6,
        "july": 7, "august": 8, "september": 9,
        "october": 10, "november": 11, "december": 12
    }

    for month, num in months.items():
        if month in name:
            year = re.search(r"(20\d{2})", name)
            if year:
                return pd.Timestamp(int(year.group()), num, 1)

    return pd.NaT

df["snapshot_date"] = df["report_file"].apply(extract_report_date)

print(df["snapshot_date"].isna().sum())
print(df["snapshot_date"].min())
print(df["snapshot_date"].max())

0
2025-04-01 00:00:00
2026-07-01 00:00:00

In [ ]:
print(
    df[["report_file", "snapshot_date"]]
    .drop_duplicates()
    .sort_values("snapshot_date")
    .to_string(index=False)
)

                   report_file snapshot_date
               FRApril2025.pdf    2025-04-01
                FR_May2025.pdf    2025-05-01
              FR_JUNE_2025.pdf    2025-06-01
     FlashReport_July_2025.pdf    2025-07-01
   FlashReport_August_2025.pdf    2025-08-01
FlashReport_September_2025.pdf    2025-09-01
  FlashReport_October_2025.pdf    2025-10-01
 FlashReport_November_2025.pdf    2025-11-01
 FlashReport_December_2025.pdf    2025-12-01
  FlashReport_January_2026.pdf    2026-01-01
 FlashReport_February_2026.pdf    2026-02-01
    FlashReport_March_2026.pdf    2026-03-01
     FlashReport_April2026.pdf    2026-04-01
       FlashReport_May2026.pdf    2026-05-01
     FlashReport_June_2026.pdf    2026-06-01
     FlashReport_July_2026.pdf    2026-07-01

In [ ]:
# Duplicate project codes within the same snapshot
dup_code = (
    df[df["project_code"].notna()]
    .groupby(["snapshot_date", "project_code"])
    .size()
    .reset_index(name="count")
)

print("Project-code/snapshot duplicates:",
      (dup_code["count"] > 1).sum())

print(
    dup_code[dup_code["count"] > 1]
    .sort_values("count", ascending=False)
    .head(20)
)

Project-code/snapshot duplicates: 52
      snapshot_date project_code  count
12228    2026-02-01    N24000319      4
12229    2026-02-01    N24000320      4
12372    2026-02-01    N24001416      4
12362    2026-02-01    N24001390      4
12338    2026-02-01    N24001323      4
12393    2026-02-01    N24001450      4
13444    2026-03-01    N24001323      4
13481    2026-03-01    N24001419      4
13657    2026-03-01    N24001792      4
13866    2026-03-01    N24002132      4
13499    2026-03-01    N24001450      4
13631    2026-03-01    N24001730      4
13478    2026-03-01    N24001416      4
13468    2026-03-01    N24001390      4
13336    2026-03-01    N24000320      4
13435    2026-03-01    N24001281      4
13428    2026-03-01    N24001263      4
12765    2026-02-01    N24002132      4
13335    2026-03-01    N24000319      4
12291    2026-02-01    N24000983      3

In [ ]:
dup_name = (
    df.groupby(["snapshot_date", "project_name"])
    .size()
    .reset_index(name="count")
)

print("Project-name/snapshot duplicates:",
      (dup_name["count"] > 1).sum())

Project-name/snapshot duplicates: 45

In [ ]:
df[
    (df["snapshot_date"] == "2026-02-01") &
    (df["project_code"] == "N24000319")
][[
    "project_name",
    "project_code",
    "agency",
    "ministry",
    "state",
    "sector",
    "original_cost_cr",
    "revised_cost_cr",
    "cumulative_expenditure_cr",
    "physical_progress_pct",
    "format"
]].to_string(index=False)

'                                                                                                                                                                                                                project_name project_code agency                              ministry state           sector  original_cost_cr  revised_cost_cr  cumulative_expenditure_cr  physical_progress_pct format\n           Construction of Balance Work of 4-Laning of the Section from Jorhat to Jhanji of NH- 37 Old from Km 453000 to Km 463000 10.000 Km, under SARDP- NE under EPC Mode in the state of Assam Pkg-I Road Works (NHIDCL)    N24000319 618439 Ministry of Road Transport & Highways ASSAM Roads & Highways            478.30           478.30                       0.00                   96.0    new\n     Construction of Balance Work of the 4-Laning of the Section from Jorhat to Jhanji of NH-37 Old from Km 477.000 to Km 490800 13.800 Km, under SARDP- NE under EPC Mode in the state of Assam Pkg-III Road Works (NHIDCL)    N24000319 618442 Ministry of Road Transport & Highways ASSAM Roads & Highways            358.72           358.72                       0.07                   99.0    new\n      Construction of Balance Work of the 4-Laning of the Section from Jorhat to Jhanji of NH-37 Old from Km 463.00 to Km 477.000 14.000 Km, under SARDP- NE under EPC Mode in the state of Assam Pkg-II Road Works (NHIDCL)    N24000319 618443 Ministry of Road Transport & Highways ASSAM Roads & Highways            438.44           438.44                       0.00                   95.0    new\nConstruction of Balance Work of the 4-Laning of the Section from Jorhat to Jhanji of NH-37 Old from Km 453.000 to Km 490.800, under SARDP- NE , under EPC Mode in the state of Assam Pkg-IV Structures & Toll Plaza (NHIDCL)    N24000319 618444 Ministry of Road Transport & Highways ASSAM Roads & Highways            279.01           279.01                       0.00                   94.0    new'

In [ ]:
df[
    (df["snapshot_date"] == "2026-03-01") &
    (df["project_code"] == "N24001281")
][[
    "project_name",
    "project_code",
    "agency",
    "ministry",
    "state",
    "sector",
    "original_cost_cr",
    "revised_cost_cr",
    "cumulative_expenditure_cr",
    "physical_progress_pct",
    "format"
]].to_string(index=False)

'                                                                                                                                                                                                                                                                                                   project_name project_code agency                              ministry     state           sector  original_cost_cr  revised_cost_cr  cumulative_expenditure_cr  physical_progress_pct format\n                                                             Construction of Major Bridge Across Sharavathi Backwaters and approches between Ambargodu and Kalasavalli Near Sigandhur in Sagar Taluk on NH 369E in the State of Karnataka on EPC mode.Job No. NH-369E-KNT-2018-19-895 dated 06.03.2019. (MoRTH)    N24001281 618144 Ministry of Road Transport & Highways KARNATAKA Roads & Highways            423.15           423.15                       0.00                   0.00    new\nRehabilitation and Up gradation to 2-lane with paved shoulder of Keifang Section Economic Corridor of NH-06 from Existing Chainage Km 30050 Keifang to Km 50360 Keifang, Design Chainage Km 27400 to Km 45040 PkgIII in the State of Mizoram under Bharatmala Pariyojna on EPC Mode Seling-Dulte - III (NHIDCL)    N24001281 618343 Ministry of Road Transport & Highways   MIZORAM Roads & Highways            292.23           292.23                       0.00                   0.00    new\n                                                               Construction of 4/6 Laning from Km 132.375 to Km 153.058 Total New Alignment length of 20.683 Km of Daboka-Dimapur Section Dimapur Bypass Nagaland Portion of NH-36 & 39 in the State of Nagaland on EPC basis under PhaseA of SARDP-NE (NHIDCL)    N24001281 618329 Ministry of Road Transport & Highways  NAGALAND Roads & Highways            819.39           819.39                       0.00                   0.00    new\n                                                                                                                          Rehabilitation & upgradation of NH - 167 from design km 187.723 to 234.434 Miryalaguda to Kodad section to two lane with paved shoulder on EPC mode in the state of Telangana (MoRTH)    N24001281 617992 Ministry of Road Transport & Highways TELANGANA Roads & Highways            322.81           322.81                     148.48                  98.14    new'

In [ ]:
import re
import numpy as np

def normalize_project_name(name):
    if pd.isna(name):
        return np.nan

    name = str(name).upper().strip()
    name = re.sub(r"\s+", " ", name)

    return name

# Normalize project names
df["project_name_normalized"] = df["project_name"].apply(
    normalize_project_name
)

# Create internal project ID
df["project_id"] = np.where(
    df["project_code"].notna(),
    df["project_code"].astype(str) + "_" +
    df["project_name_normalized"].fillna("UNKNOWN"),
    "NAME_" + df["project_name_normalized"].fillna("UNKNOWN")
)

# Check duplicates within each monthly snapshot
dup_project = (
    df.groupby(["snapshot_date", "project_id"])
      .size()
      .reset_index(name="count")
)

print(
    "Project ID/snapshot duplicates:",
    (dup_project["count"] > 1).sum()
)

print(
    dup_project[dup_project["count"] > 1]
    .sort_values("count", ascending=False)
    .head(20)
)

Project ID/snapshot duplicates: 0
Empty DataFrame
Columns: [snapshot_date, project_id, count]
Index: []

In [ ]:
print("Unique projects:", df["project_id"].nunique())
print("Snapshots:", df["snapshot_date"].nunique())
print("Total rows:", len(df))

Unique projects: 9664
Snapshots: 16
Total rows: 23115

In [ ]:
snapshot_counts = (
    df.groupby("project_id")["snapshot_date"]
      .nunique()
)

print("Projects with only 1 snapshot:",
      (snapshot_counts == 1).sum())

print("Projects with 2+ snapshots:",
      (snapshot_counts >= 2).sum())

print("Maximum snapshots for one project:",
      snapshot_counts.max())

Projects with only 1 snapshot: 1735
Projects with 2+ snapshots: 7929
Maximum snapshots for one project: 7

In [ ]:
#FEATURE ENGINEERING
df = df.sort_values(
    ["project_id", "snapshot_date"]
).reset_index(drop=True)

In [ ]:
# Previous snapshot values
df["prev_progress"] = df.groupby("project_id")[
    "physical_progress_pct"
].shift(1)

df["prev_expenditure"] = df.groupby("project_id")[
    "cumulative_expenditure_cr"
].shift(1)

df["prev_revised_cost"] = df.groupby("project_id")[
    "revised_cost_cr"
].shift(1)

In [ ]:
# Progress growth
df["progress_growth"] = (
    df["physical_progress_pct"] -
    df["prev_progress"]
)

# Expenditure growth
df["expenditure_growth"] = (
    df["cumulative_expenditure_cr"] -
    df["prev_expenditure"]
)

# Revised cost growth
df["cost_growth"] = (
    df["revised_cost_cr"] -
    df["prev_revised_cost"]
)

In [ ]:
print(df[
    [
        "project_id",
        "snapshot_date",
        "physical_progress_pct",
        "progress_growth",
        "cumulative_expenditure_cr",
        "expenditure_growth",
        "revised_cost_cr",
        "cost_growth"
    ]
].head(20))

                                           project_id snapshot_date  \
0    060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY    2025-04-01
1    060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY    2025-05-01
2    060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY    2025-06-01
3   060100093_GEVRA OC [70 MTY] (SOUTH EASTERN COA...    2026-03-01
4   10000_C2/C3 VIJAIPUR PATA PIPELINE (MINISTRY O...    2026-04-01
5   10000_C2/C3 VIJAIPUR PATA PIPELINE (MINISTRY O...    2026-05-01
6   10009_COKE DRUM STRUCTURE PACKAGE (MINISTRY OF...    2026-04-01
7   10009_COKE DRUM STRUCTURE PACKAGE (MINISTRY OF...    2026-05-01
8   10010_AUGMENTATION OF CCKPL AND IDPL PIPELINES...    2026-04-01
9   10010_AUGMENTATION OF CCKPL AND IDPL PIPELINES...    2026-05-01
10  10035_KEN-BETWA LINKING DEVELOPMENT PROJECT (D...    2026-04-01
11  10035_KEN-BETWA LINKING DEVELOPMENT PROJECT (D...    2026-05-01
12  10080_BHANDAI - FLYOVER FOR ETAWAH BOUND DOWN ...    2026-04-01
13  10080_BHANDAI - FLYOVER FOR ETAWAH BOUND DOWN ...    2026-05-01
14  10102_PHASE B CONSTRUCTION OF PERMANENT CAMPUS...    2026-04-01
15  10102_PHASE B CONSTRUCTION OF PERMANENT CAMPUS...    2026-05-01
16  10104_PHASE B OF CONSTRUCTION OF PERMANENT CAM...    2026-04-01
17  10104_PHASE B OF CONSTRUCTION OF PERMANENT CAM...    2026-05-01
18  10126_ESTABLISHMENT OF NEW GMC KODERMA (MEDICA...    2026-04-01
19  10126_ESTABLISHMENT OF NEW GMC KODERMA (MEDICA...    2026-05-01

    physical_progress_pct  progress_growth  cumulative_expenditure_cr  \
0                   77.20              NaN                    6584.29
1                   77.20              0.0                    6596.25
2                   77.20              0.0                    6617.04
3                   78.48              NaN                    6905.46
4                   65.20              NaN                     488.00
5                   68.20              3.0                     488.00
6                   60.60              NaN                     453.66
7                   69.00              8.4                     543.00
8                   36.20              NaN                     268.98
9                   41.00              4.8                     284.58
10                   0.00              NaN                    8530.86
11                   0.00              0.0                    8530.86
12                   9.00              NaN                     139.49
13                   9.00              0.0                     163.27
14                   0.00              NaN                       0.00
15                   0.00              0.0                       0.00
16                   0.00              NaN                       9.80
17                   0.00              0.0                       9.80
18                  40.00              NaN                     270.00
19                  40.00              0.0                     271.00

    expenditure_growth  revised_cost_cr  cost_growth
0                  NaN              NaN          NaN
1                11.96              NaN          NaN
2                20.79              NaN          NaN
3                  NaN         11816.40          NaN
4                  NaN          1792.00          NaN
5                 0.00          1792.00          0.0
6                  NaN           635.28          NaN
7                89.34           635.28          0.0
8                  NaN          1130.00          NaN
9                15.60          1130.00          0.0
10                 NaN         21030.00          NaN
11                0.00         21030.00          0.0
12                 NaN           250.18          NaN
13               23.78           250.18          0.0
14                 NaN          1188.97          NaN
15                0.00          1188.97          0.0
16                 NaN          1527.00          NaN
17                0.00          1527.00          0.0
18                 NaN           504.80          NaN
19                1.00           504.80          0.0

In [ ]:
df["expenditure_vs_original_ratio"] = (
    df["cumulative_expenditure_cr"] /
    df["original_cost_cr"]
)

df["expenditure_vs_revised_ratio"] = (
    df["cumulative_expenditure_cr"] /
    df["revised_cost_cr"]
)

In [ ]:
print(
    df[
        [
            "project_id",
            "snapshot_date",
            "original_cost_cr",
            "revised_cost_cr",
            "cumulative_expenditure_cr",
            "expenditure_vs_original_ratio",
            "expenditure_vs_revised_ratio"
        ]
    ].head(20)
)

                                           project_id snapshot_date  \
0    060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY    2025-04-01
1    060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY    2025-05-01
2    060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY    2025-06-01
3   060100093_GEVRA OC [70 MTY] (SOUTH EASTERN COA...    2026-03-01
4   10000_C2/C3 VIJAIPUR PATA PIPELINE (MINISTRY O...    2026-04-01
5   10000_C2/C3 VIJAIPUR PATA PIPELINE (MINISTRY O...    2026-05-01
6   10009_COKE DRUM STRUCTURE PACKAGE (MINISTRY OF...    2026-04-01
7   10009_COKE DRUM STRUCTURE PACKAGE (MINISTRY OF...    2026-05-01
8   10010_AUGMENTATION OF CCKPL AND IDPL PIPELINES...    2026-04-01
9   10010_AUGMENTATION OF CCKPL AND IDPL PIPELINES...    2026-05-01
10  10035_KEN-BETWA LINKING DEVELOPMENT PROJECT (D...    2026-04-01
11  10035_KEN-BETWA LINKING DEVELOPMENT PROJECT (D...    2026-05-01
12  10080_BHANDAI - FLYOVER FOR ETAWAH BOUND DOWN ...    2026-04-01
13  10080_BHANDAI - FLYOVER FOR ETAWAH BOUND DOWN ...    2026-05-01
14  10102_PHASE B CONSTRUCTION OF PERMANENT CAMPUS...    2026-04-01
15  10102_PHASE B CONSTRUCTION OF PERMANENT CAMPUS...    2026-05-01
16  10104_PHASE B OF CONSTRUCTION OF PERMANENT CAM...    2026-04-01
17  10104_PHASE B OF CONSTRUCTION OF PERMANENT CAM...    2026-05-01
18  10126_ESTABLISHMENT OF NEW GMC KODERMA (MEDICA...    2026-04-01
19  10126_ESTABLISHMENT OF NEW GMC KODERMA (MEDICA...    2026-05-01

    original_cost_cr  revised_cost_cr  cumulative_expenditure_cr  \
0           11816.40              NaN                    6584.29
1           11816.40              NaN                    6596.25
2           11816.40              NaN                    6617.04
3           11816.40         11816.40                    6905.46
4            1792.00          1792.00                     488.00
5            1792.00          1792.00                     488.00
6             635.28           635.28                     453.66
7             635.28           635.28                     543.00
8            1130.00          1130.00                     268.98
9            1130.00          1130.00                     284.58
10          21030.00         21030.00                    8530.86
11          21030.00         21030.00                    8530.86
12            250.18           250.18                     139.49
13            250.18           250.18                     163.27
14           1188.97          1188.97                       0.00
15           1188.97          1188.97                       0.00
16           1527.00          1527.00                       9.80
17           1527.00          1527.00                       9.80
18            250.00           504.80                     270.00
19            250.00           504.80                     271.00

    expenditure_vs_original_ratio  expenditure_vs_revised_ratio
0                        0.557216                           NaN
1                        0.558228                           NaN
2                        0.559988                           NaN
3                        0.584396                      0.584396
4                        0.272321                      0.272321
5                        0.272321                      0.272321
6                        0.714110                      0.714110
7                        0.854741                      0.854741
8                        0.238035                      0.238035
9                        0.251841                      0.251841
10                       0.405652                      0.405652
11                       0.405652                      0.405652
12                       0.557559                      0.557559
13                       0.652610                      0.652610
14                       0.000000                      0.000000
15                       0.000000                      0.000000
16                       0.006418                      0.006418
17                       0.006418                      0.006418
18                       1.080000                      0.534865
19                       1.084000                      0.536846

In [ ]:
df["months_since_prev_snapshot"] = (
    df.groupby("project_id")["snapshot_date"]
      .diff()
      .dt.days / 30.44
)

df[[
    "project_id",
    "snapshot_date",
    "months_since_prev_snapshot"
]].head(20)

,project_id,snapshot_date,months_since_prev_snapshot
0,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-04-01,NaN
1,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-05-01,0.985545
2,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-06-01,1.018397
3,060100093_GEVRA OC [70 MTY] (SOUTH EASTERN COA...,2026-03-01,NaN
4,10000_C2/C3 VIJAIPUR PATA PIPELINE (MINISTRY O...,2026-04-01,NaN
5,10000_C2/C3 VIJAIPUR PATA PIPELINE (MINISTRY O...,2026-05-01,0.985545
6,10009_COKE DRUM STRUCTURE PACKAGE (MINISTRY OF...,2026-04-01,NaN
7,10009_COKE DRUM STRUCTURE PACKAGE (MINISTRY OF...,2026-05-01,0.985545
8,10010_AUGMENTATION OF CCKPL AND IDPL PIPELINES...,2026-04-01,NaN
9,10010_AUGMENTATION OF CCKPL AND IDPL PIPELINES...,2026-05-01,0.985545
10,10035_KEN-BETWA LINKING DEVELOPMENT PROJECT (D...,2026-04-01,NaN
11,10035_KEN-BETWA LINKING DEVELOPMENT PROJECT (D...,2026-05-01,0.985545
12,10080_BHANDAI - FLYOVER FOR ETAWAH BOUND DOWN ...,2026-04-01,NaN
13,10080_BHANDAI - FLYOVER FOR ETAWAH BOUND DOWN ...,2026-05-01,0.985545
14,10102_PHASE B CONSTRUCTION OF PERMANENT CAMPUS...,2026-04-01,NaN
15,10102_PHASE B CONSTRUCTION OF PERMANENT CAMPUS...,2026-05-01,0.985545
16,10104_PHASE B OF CONSTRUCTION OF PERMANENT CAM...,2026-04-01,NaN
17,10104_PHASE B OF CONSTRUCTION OF PERMANENT CAM...,2026-05-01,0.985545
18,10126_ESTABLISHMENT OF NEW GMC KODERMA (MEDICA...,2026-04-01,NaN
19,10126_ESTABLISHMENT OF NEW GMC KODERMA (MEDICA...,2026-05-01,0.985545

In [ ]:
df["progress_velocity"] = (
    df["progress_growth"] / df["months_since_prev_snapshot"]
)

df["expenditure_velocity"] = (
    df["expenditure_growth"] / df["months_since_prev_snapshot"]
)

df[[
    "project_id",
    "snapshot_date",
    "progress_growth",
    "expenditure_growth",
    "months_since_prev_snapshot",
    "progress_velocity",
    "expenditure_velocity"
]].head(20)

,project_id,snapshot_date,progress_growth,expenditure_growth,months_since_prev_snapshot,progress_velocity,expenditure_velocity
0,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-04-01,NaN,NaN,NaN,NaN,NaN
1,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-05-01,0.0,11.96,0.985545,0.0000,12.135413
2,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-06-01,0.0,20.79,1.018397,0.0000,20.414439
3,060100093_GEVRA OC [70 MTY] (SOUTH EASTERN COA...,2026-03-01,NaN,NaN,NaN,NaN,NaN
4,10000_C2/C3 VIJAIPUR PATA PIPELINE (MINISTRY O...,2026-04-01,NaN,NaN,NaN,NaN,NaN
5,10000_C2/C3 VIJAIPUR PATA PIPELINE (MINISTRY O...,2026-05-01,3.0,0.00,0.985545,3.0440,0.000000
6,10009_COKE DRUM STRUCTURE PACKAGE (MINISTRY OF...,2026-04-01,NaN,NaN,NaN,NaN,NaN
7,10009_COKE DRUM STRUCTURE PACKAGE (MINISTRY OF...,2026-05-01,8.4,89.34,0.985545,8.5232,90.650320
8,10010_AUGMENTATION OF CCKPL AND IDPL PIPELINES...,2026-04-01,NaN,NaN,NaN,NaN,NaN
9,10010_AUGMENTATION OF CCKPL AND IDPL PIPELINES...,2026-05-01,4.8,15.60,0.985545,4.8704,15.828800
10,10035_KEN-BETWA LINKING DEVELOPMENT PROJECT (D...,2026-04-01,NaN,NaN,NaN,NaN,NaN
11,10035_KEN-BETWA LINKING DEVELOPMENT PROJECT (D...,2026-05-01,0.0,0.00,0.985545,0.0000,0.000000
12,10080_BHANDAI - FLYOVER FOR ETAWAH BOUND DOWN ...,2026-04-01,NaN,NaN,NaN,NaN,NaN
13,10080_BHANDAI - FLYOVER FOR ETAWAH BOUND DOWN ...,2026-05-01,0.0,23.78,0.985545,0.0000,24.128773
14,10102_PHASE B CONSTRUCTION OF PERMANENT CAMPUS...,2026-04-01,NaN,NaN,NaN,NaN,NaN
15,10102_PHASE B CONSTRUCTION OF PERMANENT CAMPUS...,2026-05-01,0.0,0.00,0.985545,0.0000,0.000000
16,10104_PHASE B OF CONSTRUCTION OF PERMANENT CAM...,2026-04-01,NaN,NaN,NaN,NaN,NaN
17,10104_PHASE B OF CONSTRUCTION OF PERMANENT CAM...,2026-05-01,0.0,0.00,0.985545,0.0000,0.000000
18,10126_ESTABLISHMENT OF NEW GMC KODERMA (MEDICA...,2026-04-01,NaN,NaN,NaN,NaN,NaN
19,10126_ESTABLISHMENT OF NEW GMC KODERMA (MEDICA...,2026-05-01,0.0,1.00,0.985545,0.0000,1.014667

In [ ]:
df["cost_overrun_ratio"] = (
    (df["revised_cost_cr"] - df["original_cost_cr"])
    / df["original_cost_cr"]
)

df["cost_overrun_cr"] = (
    df["revised_cost_cr"] - df["original_cost_cr"]
)

df[[
    "project_id",
    "snapshot_date",
    "original_cost_cr",
    "revised_cost_cr",
    "cost_overrun_cr",
    "cost_overrun_ratio"
]].head(20)

,project_id,snapshot_date,original_cost_cr,revised_cost_cr,cost_overrun_cr,cost_overrun_ratio
0,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-04-01,11816.40,NaN,NaN,NaN
1,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-05-01,11816.40,NaN,NaN,NaN
2,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-06-01,11816.40,NaN,NaN,NaN
3,060100093_GEVRA OC [70 MTY] (SOUTH EASTERN COA...,2026-03-01,11816.40,11816.40,0.0,0.0000
4,10000_C2/C3 VIJAIPUR PATA PIPELINE (MINISTRY O...,2026-04-01,1792.00,1792.00,0.0,0.0000
5,10000_C2/C3 VIJAIPUR PATA PIPELINE (MINISTRY O...,2026-05-01,1792.00,1792.00,0.0,0.0000
6,10009_COKE DRUM STRUCTURE PACKAGE (MINISTRY OF...,2026-04-01,635.28,635.28,0.0,0.0000
7,10009_COKE DRUM STRUCTURE PACKAGE (MINISTRY OF...,2026-05-01,635.28,635.28,0.0,0.0000
8,10010_AUGMENTATION OF CCKPL AND IDPL PIPELINES...,2026-04-01,1130.00,1130.00,0.0,0.0000
9,10010_AUGMENTATION OF CCKPL AND IDPL PIPELINES...,2026-05-01,1130.00,1130.00,0.0,0.0000
10,10035_KEN-BETWA LINKING DEVELOPMENT PROJECT (D...,2026-04-01,21030.00,21030.00,0.0,0.0000
11,10035_KEN-BETWA LINKING DEVELOPMENT PROJECT (D...,2026-05-01,21030.00,21030.00,0.0,0.0000
12,10080_BHANDAI - FLYOVER FOR ETAWAH BOUND DOWN ...,2026-04-01,250.18,250.18,0.0,0.0000
13,10080_BHANDAI - FLYOVER FOR ETAWAH BOUND DOWN ...,2026-05-01,250.18,250.18,0.0,0.0000
14,10102_PHASE B CONSTRUCTION OF PERMANENT CAMPUS...,2026-04-01,1188.97,1188.97,0.0,0.0000
15,10102_PHASE B CONSTRUCTION OF PERMANENT CAMPUS...,2026-05-01,1188.97,1188.97,0.0,0.0000
16,10104_PHASE B OF CONSTRUCTION OF PERMANENT CAM...,2026-04-01,1527.00,1527.00,0.0,0.0000
17,10104_PHASE B OF CONSTRUCTION OF PERMANENT CAM...,2026-05-01,1527.00,1527.00,0.0,0.0000
18,10126_ESTABLISHMENT OF NEW GMC KODERMA (MEDICA...,2026-04-01,250.00,504.80,254.8,1.0192
19,10126_ESTABLISHMENT OF NEW GMC KODERMA (MEDICA...,2026-05-01,250.00,504.80,254.8,1.0192

In [ ]:
df["planned_duration_days"] = (
    df["revised_doc"] - df["revised_start_date"]
).dt.days

df["elapsed_duration_days"] = (
    df["snapshot_date"] - df["revised_start_date"]
).dt.days

df[[
    "project_id",
    "snapshot_date",
    "revised_start_date",
    "revised_doc",
    "planned_duration_days",
    "elapsed_duration_days"
]].head(20)

,project_id,snapshot_date,revised_start_date,revised_doc,planned_duration_days,elapsed_duration_days
0,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-04-01,NaT,2026-03-01,NaN,NaN
1,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-05-01,NaT,2026-03-01,NaN,NaN
2,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-06-01,NaT,2026-03-01,NaN,NaN
3,060100093_GEVRA OC [70 MTY] (SOUTH EASTERN COA...,2026-03-01,2016-03-01,NaT,NaN,3652.0
4,10000_C2/C3 VIJAIPUR PATA PIPELINE (MINISTRY O...,2026-04-01,2024-05-01,NaT,NaN,700.0
5,10000_C2/C3 VIJAIPUR PATA PIPELINE (MINISTRY O...,2026-05-01,2024-05-01,NaT,NaN,730.0
6,10009_COKE DRUM STRUCTURE PACKAGE (MINISTRY OF...,2026-04-01,2022-12-01,2026-09-01,1370.0,1217.0
7,10009_COKE DRUM STRUCTURE PACKAGE (MINISTRY OF...,2026-05-01,2022-12-01,2026-09-01,1370.0,1247.0
8,10010_AUGMENTATION OF CCKPL AND IDPL PIPELINES...,2026-04-01,2024-09-01,NaT,NaN,577.0
9,10010_AUGMENTATION OF CCKPL AND IDPL PIPELINES...,2026-05-01,2024-09-01,NaT,NaN,607.0
10,10035_KEN-BETWA LINKING DEVELOPMENT PROJECT (D...,2026-04-01,2022-03-01,NaT,NaN,1492.0
11,10035_KEN-BETWA LINKING DEVELOPMENT PROJECT (D...,2026-05-01,2022-03-01,NaT,NaN,1522.0
12,10080_BHANDAI - FLYOVER FOR ETAWAH BOUND DOWN ...,2026-04-01,2021-04-01,NaT,NaN,1826.0
13,10080_BHANDAI - FLYOVER FOR ETAWAH BOUND DOWN ...,2026-05-01,2021-04-01,NaT,NaN,1856.0
14,10102_PHASE B CONSTRUCTION OF PERMANENT CAMPUS...,2026-04-01,2026-01-01,NaT,NaN,90.0
15,10102_PHASE B CONSTRUCTION OF PERMANENT CAMPUS...,2026-05-01,2026-01-01,NaT,NaN,120.0
16,10104_PHASE B OF CONSTRUCTION OF PERMANENT CAM...,2026-04-01,2026-01-01,NaT,NaN,90.0
17,10104_PHASE B OF CONSTRUCTION OF PERMANENT CAM...,2026-05-01,2026-01-01,NaT,NaN,120.0
18,10126_ESTABLISHMENT OF NEW GMC KODERMA (MEDICA...,2026-04-01,2024-02-01,NaT,NaN,790.0
19,10126_ESTABLISHMENT OF NEW GMC KODERMA (MEDICA...,2026-05-01,2024-02-01,NaT,NaN,820.0

In [ ]:
df["planned_end_date"] = df["revised_doc"].fillna(df["target_doc"])

df["planned_duration_days"] = (
    df["planned_end_date"] - df["revised_start_date"]
).dt.days

df["elapsed_duration_days"] = (
    df["snapshot_date"] - df["revised_start_date"]
).dt.days

df[[
    "project_id",
    "snapshot_date",
    "revised_start_date",
    "target_doc",
    "revised_doc",
    "planned_end_date",
    "planned_duration_days",
    "elapsed_duration_days"
]].head(20)

,project_id,snapshot_date,revised_start_date,target_doc,revised_doc,planned_end_date,planned_duration_days,elapsed_duration_days
0,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-04-01,NaT,2023-03-01,2026-03-01,2026-03-01,NaN,NaN
1,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-05-01,NaT,2023-03-01,2026-03-01,2026-03-01,NaN,NaN
2,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-06-01,NaT,2023-03-01,2026-03-01,2026-03-01,NaN,NaN
3,060100093_GEVRA OC [70 MTY] (SOUTH EASTERN COA...,2026-03-01,2016-03-01,2023-03-01,NaT,2023-03-01,2556.0,3652.0
4,10000_C2/C3 VIJAIPUR PATA PIPELINE (MINISTRY O...,2026-04-01,2024-05-01,NaT,NaT,NaT,NaN,700.0
5,10000_C2/C3 VIJAIPUR PATA PIPELINE (MINISTRY O...,2026-05-01,2024-05-01,NaT,NaT,NaT,NaN,730.0
6,10009_COKE DRUM STRUCTURE PACKAGE (MINISTRY OF...,2026-04-01,2022-12-01,2025-12-01,2026-09-01,2026-09-01,1370.0,1217.0
7,10009_COKE DRUM STRUCTURE PACKAGE (MINISTRY OF...,2026-05-01,2022-12-01,2025-12-01,2026-09-01,2026-09-01,1370.0,1247.0
8,10010_AUGMENTATION OF CCKPL AND IDPL PIPELINES...,2026-04-01,2024-09-01,NaT,NaT,NaT,NaN,577.0
9,10010_AUGMENTATION OF CCKPL AND IDPL PIPELINES...,2026-05-01,2024-09-01,NaT,NaT,NaT,NaN,607.0
10,10035_KEN-BETWA LINKING DEVELOPMENT PROJECT (D...,2026-04-01,2022-03-01,NaT,NaT,NaT,NaN,1492.0
11,10035_KEN-BETWA LINKING DEVELOPMENT PROJECT (D...,2026-05-01,2022-03-01,NaT,NaT,NaT,NaN,1522.0
12,10080_BHANDAI - FLYOVER FOR ETAWAH BOUND DOWN ...,2026-04-01,2021-04-01,2026-02-01,NaT,2026-02-01,1767.0,1826.0
13,10080_BHANDAI - FLYOVER FOR ETAWAH BOUND DOWN ...,2026-05-01,2021-04-01,2026-02-01,NaT,2026-02-01,1767.0,1856.0
14,10102_PHASE B CONSTRUCTION OF PERMANENT CAMPUS...,2026-04-01,2026-01-01,NaT,NaT,NaT,NaN,90.0
15,10102_PHASE B CONSTRUCTION OF PERMANENT CAMPUS...,2026-05-01,2026-01-01,NaT,NaT,NaT,NaN,120.0
16,10104_PHASE B OF CONSTRUCTION OF PERMANENT CAM...,2026-04-01,2026-01-01,NaT,NaT,NaT,NaN,90.0
17,10104_PHASE B OF CONSTRUCTION OF PERMANENT CAM...,2026-05-01,2026-01-01,NaT,NaT,NaT,NaN,120.0
18,10126_ESTABLISHMENT OF NEW GMC KODERMA (MEDICA...,2026-04-01,2024-02-01,2026-08-01,NaT,2026-08-01,912.0,790.0
19,10126_ESTABLISHMENT OF NEW GMC KODERMA (MEDICA...,2026-05-01,2024-02-01,2026-08-01,NaT,2026-08-01,912.0,820.0

In [ ]:
df["time_elapsed_ratio"] = np.where(
    df["planned_duration_days"] > 0,
    df["elapsed_duration_days"] / df["planned_duration_days"],
    np.nan
)

df["time_elapsed_ratio"] = df["time_elapsed_ratio"].clip(lower=0)

df["expected_progress_pct"] = (
    df["time_elapsed_ratio"] * 100
).clip(0, 100)

df["progress_gap"] = (
    df["physical_progress_pct"] - df["expected_progress_pct"]
)

df["schedule_pressure"] = (
    df["expected_progress_pct"] - df["physical_progress_pct"]
)

df[[
    "project_id",
    "snapshot_date",
    "physical_progress_pct",
    "time_elapsed_ratio",
    "expected_progress_pct",
    "progress_gap",
    "schedule_pressure"
]].head(20)

,project_id,snapshot_date,physical_progress_pct,time_elapsed_ratio,expected_progress_pct,progress_gap,schedule_pressure
0,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-04-01,77.20,NaN,NaN,NaN,NaN
1,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-05-01,77.20,NaN,NaN,NaN,NaN
2,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-06-01,77.20,NaN,NaN,NaN,NaN
3,060100093_GEVRA OC [70 MTY] (SOUTH EASTERN COA...,2026-03-01,78.48,1.428795,100.000000,-21.520000,21.520000
4,10000_C2/C3 VIJAIPUR PATA PIPELINE (MINISTRY O...,2026-04-01,65.20,NaN,NaN,NaN,NaN
5,10000_C2/C3 VIJAIPUR PATA PIPELINE (MINISTRY O...,2026-05-01,68.20,NaN,NaN,NaN,NaN
6,10009_COKE DRUM STRUCTURE PACKAGE (MINISTRY OF...,2026-04-01,60.60,0.888321,88.832117,-28.232117,28.232117
7,10009_COKE DRUM STRUCTURE PACKAGE (MINISTRY OF...,2026-05-01,69.00,0.910219,91.021898,-22.021898,22.021898
8,10010_AUGMENTATION OF CCKPL AND IDPL PIPELINES...,2026-04-01,36.20,NaN,NaN,NaN,NaN
9,10010_AUGMENTATION OF CCKPL AND IDPL PIPELINES...,2026-05-01,41.00,NaN,NaN,NaN,NaN
10,10035_KEN-BETWA LINKING DEVELOPMENT PROJECT (D...,2026-04-01,0.00,NaN,NaN,NaN,NaN
11,10035_KEN-BETWA LINKING DEVELOPMENT PROJECT (D...,2026-05-01,0.00,NaN,NaN,NaN,NaN
12,10080_BHANDAI - FLYOVER FOR ETAWAH BOUND DOWN ...,2026-04-01,9.00,1.033390,100.000000,-91.000000,91.000000
13,10080_BHANDAI - FLYOVER FOR ETAWAH BOUND DOWN ...,2026-05-01,9.00,1.050368,100.000000,-91.000000,91.000000
14,10102_PHASE B CONSTRUCTION OF PERMANENT CAMPUS...,2026-04-01,0.00,NaN,NaN,NaN,NaN
15,10102_PHASE B CONSTRUCTION OF PERMANENT CAMPUS...,2026-05-01,0.00,NaN,NaN,NaN,NaN
16,10104_PHASE B OF CONSTRUCTION OF PERMANENT CAM...,2026-04-01,0.00,NaN,NaN,NaN,NaN
17,10104_PHASE B OF CONSTRUCTION OF PERMANENT CAM...,2026-05-01,0.00,NaN,NaN,NaN,NaN
18,10126_ESTABLISHMENT OF NEW GMC KODERMA (MEDICA...,2026-04-01,40.00,0.866228,86.622807,-46.622807,46.622807
19,10126_ESTABLISHMENT OF NEW GMC KODERMA (MEDICA...,2026-05-01,40.00,0.899123,89.912281,-49.912281,49.912281

In [ ]:
df["remaining_progress_pct"] = (
    100 - df["physical_progress_pct"]
)

df["expenditure_intensity"] = np.where(
    df["physical_progress_pct"] > 0,
    df["expenditure_vs_original_ratio"] /
    (df["physical_progress_pct"] / 100),
    np.nan
)

df[[
    "project_id",
    "snapshot_date",
    "physical_progress_pct",
    "remaining_progress_pct",
    "expenditure_vs_original_ratio",
    "expenditure_intensity"
]].head(20)

,project_id,snapshot_date,physical_progress_pct,remaining_progress_pct,expenditure_vs_original_ratio,expenditure_intensity
0,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-04-01,77.20,22.80,0.557216,0.721783
1,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-05-01,77.20,22.80,0.558228,0.723094
2,060100093_GEVRA EXPANSION OCP (SECL) (35-70) MTY,2025-06-01,77.20,22.80,0.559988,0.725373
3,060100093_GEVRA OC [70 MTY] (SOUTH EASTERN COA...,2026-03-01,78.48,21.52,0.584396,0.744644
4,10000_C2/C3 VIJAIPUR PATA PIPELINE (MINISTRY O...,2026-04-01,65.20,34.80,0.272321,0.417671
5,10000_C2/C3 VIJAIPUR PATA PIPELINE (MINISTRY O...,2026-05-01,68.20,31.80,0.272321,0.399298
6,10009_COKE DRUM STRUCTURE PACKAGE (MINISTRY OF...,2026-04-01,60.60,39.40,0.714110,1.178400
7,10009_COKE DRUM STRUCTURE PACKAGE (MINISTRY OF...,2026-05-01,69.00,31.00,0.854741,1.238755
8,10010_AUGMENTATION OF CCKPL AND IDPL PIPELINES...,2026-04-01,36.20,63.80,0.238035,0.657556
9,10010_AUGMENTATION OF CCKPL AND IDPL PIPELINES...,2026-05-01,41.00,59.00,0.251841,0.614246
10,10035_KEN-BETWA LINKING DEVELOPMENT PROJECT (D...,2026-04-01,0.00,100.00,0.405652,NaN
11,10035_KEN-BETWA LINKING DEVELOPMENT PROJECT (D...,2026-05-01,0.00,100.00,0.405652,NaN
12,10080_BHANDAI - FLYOVER FOR ETAWAH BOUND DOWN ...,2026-04-01,9.00,91.00,0.557559,6.195095
13,10080_BHANDAI - FLYOVER FOR ETAWAH BOUND DOWN ...,2026-05-01,9.00,91.00,0.652610,7.251224
14,10102_PHASE B CONSTRUCTION OF PERMANENT CAMPUS...,2026-04-01,0.00,100.00,0.000000,NaN
15,10102_PHASE B CONSTRUCTION OF PERMANENT CAMPUS...,2026-05-01,0.00,100.00,0.000000,NaN
16,10104_PHASE B OF CONSTRUCTION OF PERMANENT CAM...,2026-04-01,0.00,100.00,0.006418,NaN
17,10104_PHASE B OF CONSTRUCTION OF PERMANENT CAM...,2026-05-01,0.00,100.00,0.006418,NaN
18,10126_ESTABLISHMENT OF NEW GMC KODERMA (MEDICA...,2026-04-01,40.00,60.00,1.080000,2.700000
19,10126_ESTABLISHMENT OF NEW GMC KODERMA (MEDICA...,2026-05-01,40.00,60.00,1.084000,2.710000

In [ ]:
# Check the engineered features
feature_cols = [
    "prev_progress",
    "prev_expenditure",
    "prev_revised_cost",
    "progress_growth",
    "expenditure_growth",
    "cost_growth",
    "expenditure_vs_original_ratio",
    "expenditure_vs_revised_ratio",
    "months_since_prev_snapshot",
    "progress_velocity",
    "expenditure_velocity",
    "cost_overrun_cr",
    "cost_overrun_ratio",
    "planned_duration_days",
    "elapsed_duration_days",
    "time_elapsed_ratio",
    "expected_progress_pct",
    "progress_gap",
    "schedule_pressure",
    "remaining_progress_pct",
    "expenditure_intensity"
]

print("Number of engineered features:", len(feature_cols))
print("\nMissing values:")
print(df[feature_cols].isna().sum())

print("\nInfinite values:")
print(np.isinf(df[feature_cols].select_dtypes(include=np.number)).sum())

print("\nFinal shape:", df.shape)

Number of engineered features: 21

Missing values:
prev_progress                     9924
prev_expenditure                  9664
prev_revised_cost                11844
progress_growth                   9949
expenditure_growth                9664
cost_growth                      11850
expenditure_vs_original_ratio        2
expenditure_vs_revised_ratio      3784
months_since_prev_snapshot        9664
progress_velocity                 9949
expenditure_velocity              9664
cost_overrun_cr                   3782
cost_overrun_ratio                3782
planned_duration_days            10431
elapsed_duration_days             5649
time_elapsed_ratio               10483
expected_progress_pct            10483
progress_gap                     10483
schedule_pressure                10483
remaining_progress_pct             459
expenditure_intensity             1811
dtype: int64

Infinite values:
prev_progress                    0
prev_expenditure                 0
prev_revised_cost                0
progress_growth                  0
expenditure_growth               0
cost_growth                      0
expenditure_vs_original_ratio    0
expenditure_vs_revised_ratio     0
months_since_prev_snapshot       0
progress_velocity                0
expenditure_velocity             0
cost_overrun_cr                  0
cost_overrun_ratio               0
planned_duration_days            0
elapsed_duration_days            0
time_elapsed_ratio               0
expected_progress_pct            0
progress_gap                     0
schedule_pressure                0
remaining_progress_pct           0
expenditure_intensity            0
dtype: int64

Final shape: (23115, 53)

In [ ]:
# Save final feature-engineered dataset
output_file = "PAIMANA_feature_engineered_dataset.csv"

df.to_csv(output_file, index=False)

# Download
from google.colab import files
files.download(output_file)